import type { User, Company, Department, PurchaseRequest } from "@/types"

// Mock Users
export const mockUsers: User[] = [
  {
    id: "1",
    email: "admin@acme.com",
    name: "John Admin",
    role: "admin",
    companyId: "1",
    onboardingCompleted: true,
  },
  {
    id: "2",
    email: "sarah@acme.com",
    name: "Sarah Marketing",
    role: "employee",
    companyId: "1",
    departmentId: "1",
    onboardingCompleted: true,
  },
  {
    id: "3",
    email: "mike@acme.com",
    name: "Mike Engineer",
    role: "employee",
    companyId: "1",
    departmentId: "2",
    onboardingCompleted: true,
  },
  {
    id: "4",
    email: "lisa@acme.com",
    name: "Lisa Sales",
    role: "employee",
    companyId: "1",
    departmentId: "3",
    onboardingCompleted: true,
  },
  {
    id: "5",
    email: "alex@acme.com",
    name: "Alex HR",
    role: "employee",
    companyId: "1",
    departmentId: "4",
    onboardingCompleted: true,
  },
]

// Mock Company
export const mockCompany: Company = {
  id: "1",
  name: "Acme Inc",
  size: "11-50",
  industry: "Tech",
  adminId: "1",
  createdAt: "2023-01-15T08:00:00Z",
}

// Mock Departments
export const mockDepartments: Department[] = [
  {
    id: "1",
    companyId: "1",
    name: "Marketing",
    monthlyBudget: 10000,
    currentSpent: 4500,
    employeeCount: 2,
  },
  {
    id: "2",
    companyId: "1",
    name: "Engineering",
    monthlyBudget: 20000,
    currentSpent: 12000,
    employeeCount: 8,
  },
  {
    id: "3",
    companyId: "1",
    name: "Sales",
    monthlyBudget: 15000,
    currentSpent: 9000,
    employeeCount: 3,
  },
  {
    id: "4",
    companyId: "1",
    name: "HR",
    monthlyBudget: 5000,
    currentSpent: 2000,
    employeeCount: 1,
  },
]

// Mock Purchase Requests
export const mockRequests: PurchaseRequest[] = [
  {
    id: "1",
    employeeId: "2",
    departmentId: "1",
    amount: 250,
    description: "Social media ads",
    category: "Advertising",
    status: "approved",
    aiDecisionReason: "Within budget and aligns with department goals",
    submittedAt: "2023-05-15T10:30:00Z",
    processedAt: "2023-05-15T11:45:00Z",
  },
  {
    id: "2",
    employeeId: "2",
    departmentId: "1",
    amount: 500,
    description: "Content creation tools",
    category: "Software",
    status: "approved",
    aiDecisionReason: "Essential tools for marketing team productivity",
    submittedAt: "2023-05-10T09:15:00Z",
    processedAt: "2023-05-10T10:30:00Z",
  },
  {
    id: "3",
    employeeId: "3",
    departmentId: "2",
    amount: 1200,
    description: "New development laptops",
    category: "Equipment",
    status: "pending",
    submittedAt: "2023-05-16T09:15:00Z",
  },
  {
    id: "4",
    employeeId: "3",
    departmentId: "2",
    amount: 89,
    description: "Cloud hosting services",
    category: "Infrastructure",
    status: "approved",
    aiDecisionReason: "Necessary for project deployment",
    submittedAt: "2023-05-12T14:20:00Z",
    processedAt: "2023-05-12T15:10:00Z",
  },
  {
    id: "5",
    employeeId: "4",
    departmentId: "3",
    amount: 3500,
    description: "Conference booth",
    category: "Events",
    justification: "Major industry conference with potential clients",
    status: "denied",
    aiDecisionReason: "Exceeds monthly event budget allocation",
    submittedAt: "2023-05-14T14:20:00Z",
    processedAt: "2023-05-14T16:30:00Z",
  },
  {
    id: "6",
    employeeId: "4",
    departmentId: "3",
    amount: 150,
    description: "Client lunch meeting",
    category: "Entertainment",
    status: "approved",
    aiDecisionReason: "Within per-client entertainment budget",
    submittedAt: "2023-05-13T11:00:00Z",
    processedAt: "2023-05-13T11:45:00Z",
  },
  {
    id: "7",
    employeeId: "5",
    departmentId: "4",
    amount: 750,
    description: "Team building event",
    category: "Employee Engagement",
    status: "approved",
    aiDecisionReason: "Quarterly team building budget available",
    submittedAt: "2023-05-08T10:00:00Z",
    processedAt: "2023-05-08T13:20:00Z",
  },
  {
    id: "8",
    employeeId: "2",
    departmentId: "1",
    amount: 1800,
    description: "Video production equipment",
    category: "Equipment",
    justification: "Needed for in-house content creation",
    status: "pending",
    submittedAt: "2023-05-17T09:30:00Z",
  },
  {
    id: "9",
    employeeId: "3",
    departmentId: "2",
    amount: 299,
    description: "Software licenses",
    category: "Software",
    status: "approved",
    aiDecisionReason: "Essential development tools",
    submittedAt: "2023-05-11T15:45:00Z",
    processedAt: "2023-05-11T16:30:00Z",
  },
  {
    id: "10",
    employeeId: "4",
    departmentId: "3",
    amount: 450,
    description: "Sales training materials",
    category: "Training",
    status: "approved",
    aiDecisionReason: "Within training budget and high ROI potential",
    submittedAt: "2023-05-09T13:15:00Z",
    processedAt: "2023-05-09T14:30:00Z",
  },
  {
    id: "11",
    employeeId: "5",
    departmentId: "4",
    amount: 2500,
    description: "HR software annual subscription",
    category: "Software",
    status: "denied",
    aiDecisionReason: "Exceeds allocated software budget for the quarter",
    submittedAt: "2023-05-16T11:20:00Z",
    processedAt: "2023-05-16T14:15:00Z",
  },
  {
    id: "12",
    employeeId: "3",
    departmentId: "2",
    amount: 175,
    description: "Technical books",
    category: "Training",
    status: "approved",
    aiDecisionReason: "Within personal development budget",
    submittedAt: "2023-05-15T16:00:00Z",
    processedAt: "2023-05-15T16:45:00Z",
  },
]
